### ISSUE TITLE
Cross-platform contribution scripts

### ISSUE THREAD

**Issue by PizzaCrust** [FountainMC/Fountain#1]
Currently the scripts for the Fountain implementation, only seems feasible for Unix systems. 
Please allow more cross-platform availability for other developers willingly to develop on Windows.

**Comment by Techcable** [comment]
I will have to port the scripts to python I guess :)

**Comment by phase** [comment]
MinGW has everything you need. I think adding Python scripts would complicate things. No need to get the Python interpreter running for a `curl` and a `java -jar`.

**Comment by Techcable** [comment]
@phase Python scripts won't complicate things, it'd just make it easier :)
Especially since I coded a [python patch library](https://github.com/Techcable/DiffUtils)

**Comment by phase** [comment]
You can't beat the original. Just leave the shells ones in the folder, I (and maybe others) will use them.
