### ISSUE TITLE
Switch to Mixins and ForgeGradle

### ISSUE THREAD

**Issue by phase** [FountainMC/Fountain#10]
This was bound to happen. Mixins provides a safer, cleaner option to patches, and ForgeGradle provides a simpler way to manage sources.

Since FountainForge is doing the same, should we create a FountainCommon?

**Comment by PizzaCrust** [comment]
FountainCommon?

**Comment by chibill** [comment]
Yez

**Comment by Techcable** [comment]
We don't need ForgeGradle if we use mixins.
Also, we'd need to refractor a whole bunch of stuff out into a 'FountainCommon' to help @jamierocks

**Comment by PizzaCrust** [comment]
ForgeGradle is great and a easier way if to use MixinGradle.

**Comment by Techcable** [comment]
Fixed by FountainCommon@5976ed25e4be3269647257f8354eca04c8a67053
