### ISSUE TITLE
Paper Patches and Spigot Patches

### ISSUE THREAD

**Issue by Techcable** [FountainMC/Fountain#4]
# Spigot Patches

These are important Spigot Patches that need to be ported. They can be found on [Spigot's Stash](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/spigot/browse/CraftBukkit-Patches).
Bolded are critical, italics are important.
- [ ] Configurable Crop Growth Ranges
- [ ] **'Merge tweaks and configuration'**
  - [ ] Allow merging experience orbs
  - [ ] Configurable item merge orbs
  - [ ] 'Refractor the merge algorithim to be a better experience for players'
- [ ] Per world view distances
- [ ] Fix mob spawning relative to view distance
- [ ] Handle null tile entiites 
- [ ] _Configurable item despawn rate_
- [ ] **Entity activation range**
- [ ] **Entity tracking range**
- [ ] _Close unloaded save files_
- [ ] **Hopper customizations**
  - [ ] Configurable hopperTransfer
  - [ ] ~~Configurable hopperCheck~~ (this used to be a spigot feature but is now part of [Paper](https://github.com/PaperMC/Paper))
  - [ ] Configurable hopperAmount
- [ ] Allow disabling of command logging
- [ ] Allow disabling of command tab-complete
- [ ] _Configurable messages_
- [ ] _Allow disabling of random light updates_
- [x] [**Disallow interaction with self**](https://github.com/FountainMC/Fountain/commit/5dc391c8bb08978fdf3e36c1486f74140aba46d9)
- [ ] _Plug world unload memory leak_
- [ ] Fully disable snooper when not required
- [ ] **Cap minimum player speed**
- [ ] Allow disabling of 1.6.3 structure saving
- [ ] _Don't special case x move value_
- [ ] Configurable arrow despawn rate
- [ ] **Watchdog thread**
- [ ] _Fix some chunks being sent to the client_
- [ ] Fix broken async chat
- [ ] **Fire prelogin events in offline mode**
- [ ] **Bungeecord support**
- [ ] Allow disabling zombie villager agression
- [ ] Configurable amount of netty threads
- [ ] _Prevent mineshaft saving_
- [ ] _Log cause of unexpected exceptions_
- [ ] _Save ticks lived to NBTTag_
- [ ] **Add option to nerf spawner mobs**
- [ ] _Add latebind option_
- [ ] Allow statistics to be disabled or forced
- [ ] _Fix ItemStack unbreakable code_
- [ ] _Note where an exception came from_ (entities or world ticking)
- [ ] **Improve AutoSave Mechanism**
- [ ] _Catch stalling on corrupted map data NBT tags_
- [ ] Allow toggling of zombie pigmen spawning in portal blocks
- [ ] **Highly optimized tick loop**
  - [ ] TPS Command
- [ ] _Add optional tick shuffling_
- [ ] **Cap entity collisions**
- [ ] Fix dispensing bonemeal not having the correct data
- [ ] _Spam filter exclusions_ (excludes certain commands/messages from the spam filter)
- [ ] _Allow option to silence command block console_
- [ ] Allow disablng creative item filter
- [ ] _Cap channel registrations_
- [ ] **Prevent hoppers from loading chunks**
- [ ] _Guard entity list_
- [ ] Fix ConcurrentModificationException while being idle in a vehicle
- [ ] _Descriptive kick reasons instead of nope_
- [ ] Configurable dragon death and wither spawn sounds
- [ ] **Treat bungee as online mode**
- [ ] _Give a message during UUID conversion_
- [ ] Print stack on InternalException when in debug
- [ ] **Try and use offline mode player data if online mode player data isn't found**
- [ ] _Use provided case for non existent offline players_
- [ ] _Check for blank offline player names_
- [ ] _Fix banning players by UUID_
- [ ] _Fix ban expiration dates_
- [ ] **Convert horses owner to UUID**
- [ ] _Log null tileentity owner_
- [ ] **Convert player skulls async**
- [ ] **Prevent NoClassDefError crash and notify on a physics crash**
- [ ] _Check SKULL.canPlace_
- [ ] **Fix race condition that could kill connections before they
  were initiated**
- [ ] Configurable UserCache cap
- [ ] _Validate objective score length_
- [ ] **Configurable save on stop only for UserCache**
- [ ] **Prevent unbounded IntCache growth**
- [ ] **Limit block placement and interaction packets**
- [ ] **Better item validation**
- [ ] _Further seed customization_
- [ ] _Disable ResourceLeakDetector_
- [ ] _Add more information to session.lock errors_
- [ ] _Safer json loading_
- [ ] Add command line EULA flag
- [ ] **Fix for enchanting table wiping meta when placing stacked
  items**
- [ ] _Don't spawn bonus ocelots when plugins spawn ocelots_
- [ ] _Make moved wrongly limit configurable_
- [ ] **Fix null tile entity worlds**
- [ ] _Make move to quickly limit configurable_
- [ ] **Apply NBTReadLimiter to more things**
- [ ] _Allow attribute capping_
- [ ] **Only fetch an online UUID in online mode**
- [ ] _Filter attribute modifiers which cause the attribute to go
  out of its range_
- [ ] **Plug WorldMap memory leak**
- [ ] _Fix Corrupted Trapped Chest_
- [ ] Remove uneeded validation
- [ ] Add hunger config values
- [ ] _Make debug logging toggleable_
- [ ] **Limit TNT detonations per tick**
- [ ] _Configurable hanging tick frequency_
- [ ] _Refractor ItemDoor place_
- [ ] _Use standard list for entity slices_
- ~~Allow capping tile entity tick time~~ (Don't do this! See Aikar's explination here) 
- [ ] **Use fast matches for ItemStack Dirty Check**
- [ ] _Use ConcurrentLinkedQueue for main thread tasks instead of array queue_
- [ ] Map decoration fix
- [ ] **Use map for player string lookup**
- [ ] **Clear packet queue on disconnect**
- [ ] ~~**More efficeient region file zeroing**~~
  - See [SPIGOT-2418](https://hub.spigotmc.org/jira/browse/SPIGOT-2418)
- [ ] _Don't tick blocks if neighbor chunks aren't loaded_
# Paper Patches

[Paper](https://github.com/PaperMC/Paper) has some patches for configurability and stability.
These can be found on the [GitHub repository](https://github.com/PaperMC/Paper/tree/master/Spigot-Server-Patches).
- [ ] Vanished players don't have rights
- [ ] Configurable squid spawn ranges
- [ ] Configurable cactus and reed natural growth heights
- [ ] Configurable baby zombie movement speed
- [ ] Configurable fishing time ranges
- [ ] Allow nerfed mobs to jump
- [ ] Toggle for player interact limiter
- [ ] Player Exhaustion Multipliers
- [ ] Add configurable despawn distances for living entities
- [ ] Allow for toggling of spawn chunks
- [ ] Drop falling block and tnt entities at the specified height
- [ ] Configurable speed for water flowing over lava
- [ ] Player affects spawning API
- [ ] Remove invalid mob spawner tile entities
- [ ] Optimize TileEntity Ticking
- [ ] Further improve server tick loop
- [ ] Only refresh abilities if needed
- [ ] Add async chunk load API
- [ ] Entity Origin API
- [ ] Prevent tile entity and entity crashes
- [ ] Configurable top of nether void damage
- [ ] Check online mode before converting and renaming player data
- [ ] Always tick falling blocks
- [ ] Lighting Queue
- [ ] Optimize draining
- [ ] Configurable end credits
- [ ] Fix lag from explosions processing dead entities
- [ ] Generator Settings
- [ ] Optimize explosions
- [ ] Stop updating flowing block if material has changed
- [ ] Fast draining
- [ ] Configurable lava flow speed
- [ ] Add player view distance API
- [ ] Disable explosion knockback
- [ ] Disable thunder
- [ ] Disable ice and snow
- [ ] Configurable mob spawner tick rate
- [ ] Send absolute position the first time an entity is seen
- [ ] Add BeaconEffectEvent
- [ ] Configurable container update tick rate
- [ ] Fix lava/water some times creating air instead of cobblestone
- [ ] Use UserCache for player heads
- [ ] Disable spigot tick limiters
- [ ] Configurable Chunk IO Thread Base Count
- [ ] Don't create Region File's when checking if chunk exists
- [ ] Don't create a chunk just to unload it
- [ ] Add PlayerInitialSpawnEvent
- [ ] Disable chest cat detection
- [ ] Ensure commands are not ran async
- [ ] All chunks are slime spawn chunks toggle
- [ ] Add Location support to tab completers (vanilla feature
- [ ] Optimize Pathfinding
- [ ] Optimize getBlockData
- [ ] Avoid hopper searches if there are no items
- [ ] Expose server CommandMap
- [ ] Be a bit more informative in maxHealth exception
- [ ] Graduate bungeecord chat API from spigot subclasses
- [ ] Player Tab List and Title APIs
- [ ] Ensure inv drag is in bounds
- [ ] Change implementation of (tile)entity removal list
- [ ] Add configurable portal search radius
- [ ] Add velocity warnings
- [ ] Fix inter-world teleportation glitches
- [ ] Add exception reporting event
- [ ] Don't nest if we don't need to when cerealising text
- [ ] Disable Scoreboards for non players by default
- [ ] Add methods for working with arrows stuck in living entities
- [ ] Complete resource pack API
- [ ] Re-add Spigot's hopper-check feature
- [ ] Chunk save queue improvements
- [ ] Chunk Save Reattempt
- [ ] Default loading permissions.yml before plugins
- [ ] Allow Reloading of Custom Permissions
- [ ] Remove Metadata on reload
- [ ] Undead horse leashing
- [ ] Fix Furnace cook time bug
- [ ] Handle Item Meta Inconsistencies
- [ ] Configurable Non Player Arrow Despawn Rate
- [ ] Add World Util Methods
- [ ] Optimized Light Level Comparisons
- [ ] Pass world to Village creation
- [ ] Custom replacement for eaten items
- [ ] Set health before death event
- [ ] handle NaN health/absorb values and repair bad data
- [ ] Catch Async PlayerChunkMap operations
- [ ] Support offline mode in whitelist command as well
- [ ] Fix SkullCache case bug
- [ ] Waving banner workaround
- [ ] Use a Shared Random for Entities
- [ ] Don't teleport dead entities
- [ ] Optimize Chunk Access
- [ ] Configurable spawn chances for skeleton horses
- [ ] Optimize isValidLocation for inlining
- [ ] Use correct item in arrow pickup event
- [x] [Fix cooked fish legacy import](https://github.com/FountainMC/Fountain/commit/85e1778674d8b8e94ae0362f67c106ae7bba1d8f)
- [ ] Prevent possible infinite loop in BlockPosition iterator
- [ ] Access items by EquipmentSlot
- [ ] Check async, remove unused vars, GH-159
- [ ] Option to disable BlockPhysicsEvent for Redstone
- [ ] Entity AddTo/RemoveFrom World Events
- [ ] Configurable Chunk Inhabited Timer
- [ ] EntityPathfindEvent
- [ ] Prevent Waterflow BlockFromToEvent from loading chunks
- [ ] Minecart drop name workaround
- [ ] Reduce IO ops opening a new region file.
- [ ] Sanitise RegionFileCache and make configurable.
- [ ] Add getEntity by UUID API
- [ ] Use Optimized Collections
- [ ] Do not load chunks for light checks
- [ ] Add PlayerUseUnknownEntityEvent
- [ ] Fix reducedDebugInfo not initialized on client
- [ ] Configurable Grass Spread Tick Rate
- [ ] Configurable Keep Spawn Loaded range per world
- [ ] Fix Cancelling BlockPlaceEvent triggering physics
- [ ] Don't spam reload spawn chunks in nether/end
- [ ] Remove Debug checks from DataBits
- [ ] Option to use vanilla per-world scoreboard coloring on names
- [ ] Workaround for setting passengers on players
- [ ] SPIGOT-1903: Update PlayerConnection on teleporting players
- [ ] Remove unused World Tile Entity List
- [ ] Don't tick Skulls - unused code
- [ ] Fix some players not being kicked on shutdown
- [ ] Configurable Player Collision
- [ ] Add handshake event to allow plugins to handle client
- [ ] Water mobs should only spawn in the water
- [ ] Fix Bugs with Spigot Mob Spawn Logic
- [ ] Configurable RCON IP address
- [ ] Prevent Fire from loading chunks
- [ ] Implement PlayerLocaleChangeEvent
- [ ] EntityRegainHealthEvent isFastRegen API
- [ ] Add ability to configure frosted_ice properties
- [ ] Vehicle Event Cancellation Changes
- [ ] Arrow pickup rule API
- [ ] SPIGOT-1401: Fix dispenser, dropper, furnace placement
- [ ] Improve Minecraft Hopper Performance
- [ ] remove null possibility for getServer singleton
- [ ] Improve Maps (in item frames) performance and bug fixes
- [ ] LootTable API & Replenishable Lootables Feature
- [ ] Do not load chunks for pathfinding
- [ ] Entity Tracking Improvements
- [ ] Don't save empty scoreboard teams to scoreboard.dat
- [ ] Do not mark chunks as active for neighbor updates
- [ ] Fix Chunk Unload Queue Issues
- [ ] System property for disabling watchdoge
- [ ] Optimize EAR
- [ ] Optimize UserCache / Thread Safe
- [ ] MC-99914 - ensure EntityItem loads before EntityPotion
- [ ] Avoid blocking on Network Manager creation
- [ ] Optional old TNT cannon behaviors
- [ ] Faster redstone torch rapid clock removal
- [ ] Ensure Chunks never ever load async
- [ ] Add server-name parameter
- [ ] Re-add tileEntityTick.startTiming Spigot removed
- [ ] Only send Dragon/Wither Death sounds to same world
- [x] [Fix FallingBlocks being stuck on fences](https://github.com/FountainMC/Fountain/commit/7017600ace995657c228ac21ad854c263a75c16e)
- [ ] MC-80966 - Always send chunk sections

**Comment by PizzaCrust** [comment]
- Configurable Crop Growth **Rages**

lol

**Comment by Techcable** [comment]
Entity Activation Range and Entity Tracking Range are blocked on the entity api.

**Comment by phase** [comment]
## Converting a patch
- Choose a patch.
- Find what classes were changed.
- Search for them in [spigot2mcp.srg](https://raw.githubusercontent.com/Techcable/MinecraftMappings/master/1.9.4/spigot2mcp.srg) and find the MCP mapped class name.
- Edit the code.
- Commit using the patch's author.
  - Example: The author of [Disallow Interaction with Self](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/spigot/browse/CraftBukkit-Patches/0031-Disallow-Interaction-With-Self.patch) is `md_5 <md_5@live.com.au>`, so we want to [commit with that author](https://github.com/FountainMC/Fountain/commit/5dc391c8bb08978fdf3e36c1486f74140aba46d9) (`git commit --author="md_5 <md_5@live.com.au>"`). 
  - If the original commit doesn't have a very descriptive commit message, make your own!
- Push the code and edit the above list with a link to the commit in this repository.

**Comment by phase** [comment]
This is being closed because implementing these goes against the GPL license.

Thanks, Bukkit. Who knew a commit from [2011](https://github.com/Bukkit/Bukkit/commit/6255d1794c4995b65dbd3db8b857a7d356266c5e) could harm so much.

**Comment by sgdc3** [comment]
That sucks :(

**Comment by phase** [comment]
@sgdc3 We can implement the patches that are MIT licensed.

```
[6/15/16 18:04:08] <Techcable> phase_: Aikar's patches all already MIT licensed, I'll MIT license my pathes, Byteflux hates the GPL so we can probably get him to relicense his code, and that should be enough to get the server running smoothly
```

Reopening this _for now_.

**Comment by sgdc3** [comment]
What about the patches from spigot?

**Comment by minecrafter** [comment]
Only patches that are licensed under MIT will be merged, for licensing reasons.

**Comment by phase** [comment]
@sgdc3 Anything under MIT can be merged, like [Aikar's patches](https://hub.spigotmc.org/stash/plugins/servlet/search?q=project%3ASPIGOT%20repo%3Aspigot%20Aikar).

**Comment by sgdc3** [comment]
I know, but someone should mark the gpl licensed patches  in the list above.

**Comment by phase** [comment]
That list is like 3003003450034060 entries. I'll just list MIT authors at the top.

**Comment by Techcable** [comment]
We'll handle most of this later, after we have bukkit feature parity, since many of the patches require it.
Then I'll go around trying to get people to MIT relicense their patches.
